// ==============================================================
// Nothing in this repository is a picture typed as text
//
// Every mark this project shows is drawn, as an SVG on currentColor, so it
// sits on the same baseline, takes the colour around it and looks the same on
// every machine. A typed picture — an emoji — does none of that: it arrives in
// the platform's own colours at the platform's own weight, and it is what made
// a workspace of line art look like a chat app.
//
// The rule is not only about the screen. A commit body, a release note, the
// README and a comment in the build config are all read by strangers, and a
// pictograph in any of them is decoration on a record people rely on. So this
// reads every text file the repository ships — the app, the checks, the Rust,
// the build config, the hooks, the docs and the workflows — and fails on one,
// naming the file, the line and the character. The commit-msg hook applies the
// same rule to the message itself.
//
// It covers what the app writes on screen AND what it asks a model to write,
// because an answer full of ticks and warning signs ends up on the same
// screen.
//
// Run with: npm run check:no-emoji
// ==============================================================
import { readdirSync, readFileSync, statSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');

// Pictographs, flags and anything wearing the emoji presentation selector.
//
// A few marks in the same block are plain typography, not pictures: a tick, a
// cross, a chevron, a four-pointed star. They are one colour, they take the
// colour of the text around them, and they are how a terminal line says a step
// finished. Those are named here and allowed; everything else in the block —
// the warning sign, the green tick, the red cross — is a picture.
const MARKS = '✓✔✗✘✕✖✦✧★☆❯❮·•—–…';
const PICTURE = new RegExp(`(?![${MARKS}])[\\u{1F000}-\\u{1FAFF}\\u{1F1E6}-\\u{1F1FF}\\u{2600}-\\u{27BF}\\u{2B00}-\\u{2BFF}\\u{FE0F}]`, 'u');

// Kept on purpose, each for a reason. A test case is not decoration — but the
// reason goes here, beside the others, rather than passing silently.
const ALLOWED = new Map([
  // Takes pictures OUT of an answer before it is written to a file.
  ['src/js/export-format.js', 'it removes them from exported text'],
  // Proves that stripping works.
  ['scripts/checks/export.mjs', 'it checks they are removed from exports'],
  // Proves a multi-byte character survives being split across network chunks.
  ['scripts/checks/stream-sse.mjs', 'it checks one survives a split stream'],
]);

// Directories that hold third-party or generated bytes, not this project's
// text: bundled libraries, Python wheels, images, and the embedding model's
// vocabulary, which lists characters because it must tokenise them.
const SKIP_DIRS = new Set(['vendor', 'wheels', 'assets', 'models', 'node_modules', 'target', 'gen']);
const EXTS = ['.js', '.mjs', '.rs', '.html', '.css', '.json', '.toml', '.txt', '.md', '.yml', '.yaml'];

// Walked whole. Everything this project writes lives under one of these.
const ROOTS = ['src', 'scripts', 'src-tauri/src', 'src-tauri/capabilities', 'docs', '.github'];
// Named one by one, so a local note (*.local.md, which is never committed) is
// never read by a check that prints the lines it finds.
const ROOT_FILES = [
  'README.md', 'CHANGELOG.md', 'CONTRIBUTING.md', 'CODE_OF_CONDUCT.md',
  'MODES_GUIDE.txt', 'package.json',
  'src-tauri/Cargo.toml', 'src-tauri/tauri.conf.json',
  '.githooks/pre-commit', '.githooks/commit-msg',
];

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      if (!SKIP_DIRS.has(name)) out.push(...walk(full));
    } else if (EXTS.some((e) => name.endsWith(e))) out.push(full);
  }
  return out;
}

const files = [];
for (const r of ROOTS) {
  const full = join(root, r);
  if (existsSync(full)) files.push(...walk(full));
}
for (const f of ROOT_FILES) {
  const full = join(root, f);
  if (existsSync(full)) files.push(full);
}

let pass = 0;
let fail = 0;

// A root that stopped existing would make this check quietly read nothing.
if (files.length < 200) {
  fail++;
  console.log(`  FAIL  only ${files.length} files were read — a root has moved, and this check is not looking at the repository`);
} else {
  pass++;
  console.log(`  ok    ${files.length} text files read across the app, the checks, the Rust, the build config, the hooks and the docs`);
}

const found = [];
for (const file of files) {
  const rel = relative(root, file).split('\\').join('/');
  const lines = readFileSync(file, 'utf8').split('\n');
  const hits = [];
  lines.forEach((line, i) => {
    const m = line.match(PICTURE);
    if (m) hits.push(`${rel}:${i + 1}  ${m[0]}  ${line.trim().slice(0, 90)}`);
  });
  if (!hits.length) continue;
  if (ALLOWED.has(rel)) { pass++; console.log(`  ok    ${rel} keeps them — ${ALLOWED.get(rel)}`); continue; }
  found.push(...hits);
}
if (found.length) {
  fail++;
  console.log('  FAIL  a picture is typed as text where a drawn mark or a word belongs:');
  for (const hit of found.slice(0, 40)) console.log(`          ${hit}`);
  if (found.length > 40) console.log(`          …and ${found.length - 40} more`);
} else {
  pass++;
  console.log('  ok    no picture is typed as text anywhere this repository ships');
}

// The list is kept exact: an entry that no longer needs to be there comes off.
for (const [rel, why] of ALLOWED) {
  const full = join(root, rel);
  const still = readFileSync(full, 'utf8').match(PICTURE);
  if (still) { pass++; continue; }
  fail++;
  console.log(`  FAIL  ${rel} is on the kept list (${why}) and has none — take it off the list`);
}

console.log(`\n${pass} passed, ${fail} failed  (no typed pictures)`);
process.exit(fail ? 1 : 0);
